default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# development:
#   adapter: mysql2
#   host: localhost
#   port: 3306
#   timeout: 5000
#   pool: 25
#   username: root
#   password: root
#   database: tms_development

development:
  <<: *default
  database: db/development.sqlite3

attendance:
  adapter: mysql2
  host: 192.168.0.50
  port: 17770
  timeout: 5000
  pool: 25
  username: root
  password: 
  database: zkeco_db

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
