default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  timeout: 5000
  pool: 25
  username: username
  password: password

development:  
  << *default
  database: tms_development

test:
  <<: *default
  database: tms_test

production:
  <<: *default
  database: tms_prod
